### PR TITLE
feat: handler use deserialization version of the message with test_serialization=true #86

### PR DESCRIPTION
**Pull request by jaugustin**
Hello

This fix issue #86 it allow to completely test serialization/deserialization flow in messageHandler

### CODE REVIEW

**Comment by jaugustin** [comment]
The failing test in code coverage is flaky, like on 1.x branch

**Comment by jaugustin** [comment]
@kbond @nikophil Ican you review the MR, and tell me if more work is needed ?

**Comment by kbond** [comment]
Thanks for finding and fixing this issue @jaugustin! Just a question: with this PR, is there still value for the serialization test in `TestTransport::send()`? I'm thinking if you aren't actually processing the messages this is still valuable but I'd appreciate your thoughts!

**Comment by jaugustin** [comment]
> Thanks for finding and fixing this issue @jaugustin! Just a question: with this PR, is there still value for the serialization test in `TestTransport::send()`? I'm thinking if you aren't actually processing the messages this is still valuable but I'd appreciate your thoughts!

I think removing the test in the send part could be a breaking change, if devs rely on testing serialization only by sending a message and not processing it.

In a next major version maybe remove it from the send part, or do a bigger refactoring to allow to store the serialized version in a queue, that way, we test the serialization on sending and the deserialization on processing, to be more align with real transport. 

If I take the pragmatic way, leave it, 2 tests is better than one ;)

**Review by kbond — APPROVED** [review]

**Comment by kbond** [comment]
Thanks @jaugustin!

**Pull request merged**
