### PR TITLE
fix: allows to use options configuration

### LINKED ISSUE #79: transport options are not processed when configure in the options
In the factory, the options array is ignored so it's not possible to use it to specify options instead of in the dsn. 

For example: 

```yaml 
my_queue:
  dsn: 'test://'
     options:
        queue_name: low
        disable_retries: false
``` 

or 

```php 
$messengerConfig->transport('my_queue')
  ->dsn('test://')
    ->options([
       'queue_name' => 'low', 
       'disabled_retries' => false,
    ])
```

Is there any possible problem to merge options with the parsed options from dsn to allow to use the array syntax ? 

I am willing to make a pull-request, if you think it's pertinent. 

Thanks !

### PR DESCRIPTION
**Pull request by aegypius**
Fixes #79

### CODE REVIEW

**Comment by nikophil** [comment]
@kbond don't you think we could make methods `TestTransport::isIntercepting()`, `isCatchingExceptions()` and so on public? this way we could test this PR

**Comment by kbond** [comment]
> don't you think we could make methods TestTransport::isIntercepting(), isCatchingExceptions() and so on public?

I don't have a problem with this.

**Review by kbond — APPROVED** [review]
This is really nice @aegypius!

**Review by nikophil — APPROVED** [review]

**Review by kbond — CHANGES_REQUESTED** [review]
@aegypius, could you fix the deprecations in `TestTransportFactoryTest`?

**Comment by aegypius** [comment]
> @aegypius, could you fix the deprecations in `TestTransportFactoryTest`?

Working on it

**Comment by aegypius** [comment]
Should not `self::$supportDelayStamp` be resetted too ?  https://github.com/aegypius/messenger-test/blob/allows-options-based-configuration/src/Transport/TestTransport.php#L337

**Comment by kbond** [comment]
> Should not self::$supportDelayStamp be resetted too 

I'm thinking yes but @nikophil, can you confirm?

**Comment by nikophil** [comment]
not sure this is needed:

`TestTransport::resetAll()` is called in a `#[After]` hook in order to reset everything in `TestTransport` that could have changed in the test execution: including all different states (`$queued`, `$rejected`...) but also `$intercept` and `$catchExceptions` which can be modified by methods `catchExceptions()`/`throwExceptions()`  and `unblock()`/`intercept()`

Since we're not allowing `$supportDelayStamp` to be modified (and we should not do this: this behavior will be the default one in a further major version, and could not be disabled), it is not needed to reset it

**Review by nikophil — APPROVED** [review]

**Comment by kbond** [comment]
> not sure this is needed:

Ok, let's leave as is for now.

**Review by kbond — APPROVED** [review]

**Comment by kbond** [comment]
Thank you @aegypius!

**Pull request merged**
