### PR TITLE
fix: always collect messages in TestTransport::$queue

### LINKED ISSUE #61: 1.6.0 breaks most of my tests
First of all, sorry for the vague issue.

When updating to 1.6.0, most of my tests fail. Everything up to 1.7.1 does not fix it. I think it is most likely related to #55.

Unfortunately I don't have a very good description of what is happening. It seems that messages are simply not being delivered in tests that don't use the `InteractsWithMessenger` trait. So those tests fail at various random points.

I use `test://?intercept=false&catch_exceptions=false` configuration and the workaround for [doctrine detached entities](https://github.com/zenstruck/messenger-test#detached-doctrine-entities).

I started working on an reproducer repo, but so far have not been able to reproduce it in a fresh project. Will take another look in the next few days.

Do you have any ideas/pointers that could help me debug/reproduce this?

### PR DESCRIPTION
**Pull request by nikophil**
fixes #61

### CODE REVIEW

**Comment by kbond** [comment]
Hoping @gndk can verify this fix before merging.

**Comment by nikophil** [comment]
That's what I was thinking 😇

**Comment by gndk** [comment]
Trying it out now!

**Comment by gndk** [comment]
@nikophil @kbond Everything green, works perfectly with this fix! 👍 Thanks!

**Comment by kbond** [comment]
Great, thanks for confirming! Released 1.7.2

**Pull request merged**
